grid_map_topic: /grid_map_loader_demo/grid_map
grid_map_visualizations:
  - name: elevation_points
    type: point_cloud
    params:
     layer: elevation
  - name: traversability_grid
    type: occupancy_grid
    params:
      layer: traversability
      data_min: -10.0
      data_max: 10.0

